services:
  okserver:
    image: alpine:latest
    volumes:
      - ./okserver/okserver:/okserver
    command: /okserver

  lugclient:
    image: golang:alpine
    volumes:
      - ../:/app
    working_dir: /app/simulation
    command: [sleep, infinity]
